### ISSUE TITLE
Failed on TU116.rom

### ISSUE THREAD

**Issue by UrielCh** [Marvo2011/NVIDIA-vBIOS-VFIO-Patcher#2]
the rom is also available here:
https://www.techpowerup.com/vgabios/221083/221083

```bash
 python nvidia_vbios_vfio_patcher.py  -i TU116.rom -o TU116Patched.rom
Opening the ROM file...
Scanning for ROM offsets...
ROM footer for RTX 2060 found!
Offsets found!
Running sanity checks...
Traceback (most recent call last):
  File "nvidia_vbios_vfio_patcher.py", line 213, in <module>
    main()
  File "nvidia_vbios_vfio_patcher.py", line 191, in main
    rom.run_sanity_tests(args.ignore_sanity_check)
  File "nvidia_vbios_vfio_patcher.py", line 107, in run_sanity_tests
    "footer, found %d" % npds_count)
__main__.CheckException: Expected only one 'NPDS' marker between header and footer, found 3
```

**Comment by Marvo2011** [comment]
Have you searched for a solution? Seams a very rare / card / bios.

**Comment by UrielCh** [comment]
Nop, I set up a windows 11 without virtualization.

For my next setup, that will be easier.
